<ns0:test-suite xmlns:ns0="urn:model.allure.qatools.yandex.ru" start="1535204979940" stop="1535204981938">
  <name>test_collections</name>
  <labels/>
  <test-cases>
    <test-case start="1535204979940" status="passed" stop="1535204980902">
      <description>
            用例描述：查看用户'da1677475c27'的Collections
        </description>
      <name>TestCollections.test_collections_01</name>
      <attachments>
        <attachment source="846b70c9-4de8-495f-8d5c-6f4634a77d27-attachment.txt" title="Captured log call" type="text/plain"/>
      </attachments>
      <labels>
        <label name="feature" value="Home"/>
        <label name="story" value="Collections"/>
        <label name="severity" value="normal"/>
        <label name="thread" value="22732-MainThread"/>
        <label name="host" value="xiaoxideMacBook-Pro.local"/>
        <label name="framework" value="pytest"/>
        <label name="language" value="cpython3"/>
      </labels>
      <steps/>
    </test-case>
    <test-case start="1535204980903" status="failed" stop="1535204981938">
      <description>
            用例描述：查看用户'95c34f9cc50c'的Collections
        </description>
      <name>TestCollections.test_collections_02</name>
      <failure>
        <message>AssertionError: </message>
        <stack-trace>self = &lt;test_collections.TestCollections object at 0x110fa4438&gt;
action = 'release'

    @pytest.allure.feature('Home')
    @allure.severity('blocker')
    @allure.story('Collections')
    def test_collections_02(self, action):
        """
                用例描述：查看用户'95c34f9cc50c'的Collections
            """
        conf = Config()
        data = Collections()
        test = Assert.Assertions()
        request = Request.Request(action)
    
        host = conf.host_debug
        req_url = 'http://' + host
        urls = data.url
        params = data.data
        headers = data.header
    
        api_url = req_url + urls[1]
        response = request.post_request(api_url, params[1], headers[1])
&gt;       assert test.assert_code(response['code'], 208)

TestCase/test_collections.py:65: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = &lt;Common.Assert.Assertions object at 0x111119748&gt;, code = 200
expected_code = 208

    def assert_code(self, code, expected_code):
        """
            验证response状态码
            :param code:
            :param expected_code:
            :return:
            """
        try:
&gt;           assert code == expected_code
E           AssertionError

Common/Assert.py:27: AssertionError</stack-trace>
      </failure>
      <attachments>
        <attachment source="c1f45a69-fa3d-45cf-ba88-c6d621a0333c-attachment.txt" title="Captured log call" type="text/plain"/>
      </attachments>
      <labels>
        <label name="feature" value="Home"/>
        <label name="story" value="Collections"/>
        <label name="severity" value="blocker"/>
        <label name="thread" value="22732-MainThread"/>
        <label name="host" value="xiaoxideMacBook-Pro.local"/>
        <label name="framework" value="pytest"/>
        <label name="language" value="cpython3"/>
      </labels>
      <steps/>
    </test-case>
  </test-cases>
</ns0:test-suite>
